version: '3.8'
services:

  php-apache:
      build:
        context: ./resources/${PHPVERSION}
      container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
      ports:
        - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"        
      volumes: 
        - ${DOCUMENT_ROOT-./src}:/var/www/laravel_docker
        #- ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
        - ${LOG_DIR-./logs/apache2}:/var/log/apache2
        - ./resources/default.conf:/etc/apache2/sites-enabled/000-default.conf
      depends_on:
        - database
    
      environment:
        APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
        PMA_PORT: ${HOST_MACHINE_PMA_PORT}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 

  database:
      build:
        context: "./resources/${DATABASE}"
      container_name: '${COMPOSE_PROJECT_NAME}-${DATABASE}'
      restart: 'always'
      ports:
        - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
      volumes: 
        - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
        - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
        - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
      links:
        - database
      environment:
        PMA_HOST: database
        PMA_PORT: 3306
        PMA_USER: root
        PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        UPLOAD_LIMIT: ${UPLOAD_LIMIT}
        MEMORY_LIMIT: ${MEMORY_LIMIT}
      ports:
        - '${HOST_MACHINE_PMA_PORT}:80'
      volumes: 
        - /sessions
        - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

